"""The gate that keeps the threading numbers honest.

If the Viterbi DP stops running without the GIL, every speedup this fork claims becomes
fiction -- and nothing else in the suite would notice, because the outputs are identical
either way. `tests/test_read_selection.py` drives a pure-Python stub model, so its
threading test passes with the GIL held; the Tier 3 thread-invariance test compares
digests; and no test asserts wall-clock or scaling.

So this check is load-bearing, and the tests below are about the check itself. The one
that matters is `test_a_release_around_something_else_does_not_satisfy_the_check`: that is
exactly the false green the file-wide `grep -c ... hmm.c` allowed, and it is not
hypothetical -- `subseq_viterbi` and `_update_tables_for_subseq` are still the old object
path, and putting them under `nogil` is the obvious next optimisation.
"""
import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                                'scripts'))

from assert_gil_release import (DP_CALL, dp_call_offsets, gil_released_spans,
                                unguarded_dp_calls)

GENERATED = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                         'hmm', 'hmm.c')
needs_build = unittest.skipUnless(os.path.isfile(GENERATED),
                                  'hmm/hmm.c is generated by `make build`')

#: The shape Cython emits for `with nogil:`, reduced to what this check reads.
GUARDED = '\n'.join([
    '  {',
    '      PyThreadState *_save;',
    '      Py_UNBLOCK_THREADS',
    '      __Pyx_FastGIL_Remember();',
    '      /*try:*/ {',
    '        __pyx_v_fill_status = %sargs);' % DP_CALL,
    '      }',
    '      /*finally:*/ {',
    '          __Pyx_FastGIL_Forget();',
    '          Py_BLOCK_THREADS',
    '      }',
    '  }',
])

UNGUARDED = '  __pyx_v_fill_status = %sargs);' % DP_CALL

ELSEWHERE = '\n'.join([
    '  {',
    '      PyThreadState *_save;',
    '      Py_UNBLOCK_THREADS',
    '      __pyx_f_3hmm_3hmm_subseq_viterbi(other);',
    '      Py_BLOCK_THREADS',
    '  }',
])


class TestTheGilCheckFollowsTheDpCall(unittest.TestCase):
    def test_the_emitted_nogil_block_satisfies_the_check(self):
        self.assertEqual(unguarded_dp_calls(GUARDED), [])

    def test_a_bare_call_does_not_satisfy_the_check(self):
        self.assertEqual(len(unguarded_dp_calls(UNGUARDED)), 1)

    def test_a_release_around_something_else_does_not_satisfy_the_check(self):
        """The false green the previous file-wide `grep -c` allowed: a `with nogil:` on a
        different function keeps the count >= 1 while the DP holds the GIL."""
        source = ELSEWHERE + '\n' + UNGUARDED

        self.assertEqual(len(unguarded_dp_calls(source)), 1)

    def test_one_guarded_call_does_not_excuse_a_second_unguarded_one(self):
        """Every call must be covered, not just the first one found."""
        source = GUARDED + '\n' + UNGUARDED

        self.assertEqual(len(unguarded_dp_calls(source)), 1)

    def test_the_underlying_calls_are_accepted_too(self):
        """A different Cython release may emit PyEval_SaveThread directly."""
        source = '\n'.join([
            '  _save = PyEval_SaveThread();',
            UNGUARDED,
            '  PyEval_RestoreThread(_save);',
        ])

        self.assertEqual(unguarded_dp_calls(source), [])

    def test_a_call_after_the_gil_comes_back_is_not_covered(self):
        """The span ends at the FIRST re-acquire; anything later holds the GIL again."""
        source = GUARDED + '\n' + UNGUARDED + '\n      Py_BLOCK_THREADS'

        self.assertEqual(len(unguarded_dp_calls(source)), 1)

    def test_the_declaration_and_the_definition_are_not_calls(self):
        """Cython emits the symbol three times and only one of them runs anything. Counting
        the other two reports permanently unguarded "calls" and fails a correct build."""
        source = '\n'.join([
            'static int %sX, Y);' % DP_CALL,
            'static int %sX a, Y b) { return 0; }' % DP_CALL,
            GUARDED,
        ])

        self.assertEqual(len(dp_call_offsets(source)), 1)
        self.assertEqual(unguarded_dp_calls(source), [])

    def test_a_call_on_a_line_that_mentions_static_is_still_a_call(self):
        """`'static' not in prefix` is a substring test, not "this line is a declaration".

        Any genuine DP call whose line prefix happens to contain the token drops out of the
        call list -- and if one other guarded call remains, `unguarded_dp_calls` returns []
        and the gate exits 0. That is a FALSE PASS, which is the direction that matters:
        this check exists precisely to keep working when the generated C changes shape.
        """
        source = 'static double __pyx_v_x; __pyx_v_fill_status = %sargs);' % DP_CALL

        self.assertEqual(len(dp_call_offsets(source)), 1)
        self.assertEqual(len(unguarded_dp_calls(GUARDED + '\n' + source)), 1)

    def test_a_missing_dp_is_an_error_and_not_a_pass(self):
        """Renaming the Cython function must break this loudly rather than quietly."""
        self.assertRaises(ValueError, unguarded_dp_calls,
                          '{ Py_UNBLOCK_THREADS other(); Py_BLOCK_THREADS }')

    def test_a_release_with_no_re_acquire_covers_nothing(self):
        source = '  Py_UNBLOCK_THREADS\n' + UNGUARDED

        self.assertEqual(len(unguarded_dp_calls(source)), 1)


class TestTheGeneratedExtension(unittest.TestCase):
    @needs_build
    def test_every_dp_call_in_the_shipped_extension_runs_without_the_gil(self):
        with open(GENERATED) as handle:
            source = handle.read()

        self.assertEqual(unguarded_dp_calls(source), [])

    @needs_build
    def test_the_shipped_extension_calls_the_dp_at_all(self):
        """Non-vacuity against the real artefact: an empty call list would make the
        assertion above pass for the wrong reason, which is why it raises instead."""
        with open(GENERATED) as handle:
            source = handle.read()

        self.assertEqual(len(dp_call_offsets(source)), 1)
        self.assertEqual(len(gil_released_spans(source)), 1)
