"""Backward-compatible re-exports for background fitting modules."""
from advntr.background_estimator import (
    ABLATION_EPSILON,
    BackgroundFit,
    FitterError,
    GRAMMAR_COMPONENT,
    HYPERPARAMETERS,
    MAX_PROBABILITY,
    SETTINGS_MIN_SUPPORTING_READ_COUNT,
    SIMULATED_DISCLAIMERS,
    SINK_SCHEMA,
    SINK_VERSION,
    artifact_document,
    class_of,
    default_disclaimers,
    fit_background,
    grammar_states,
    is_compound,
    median,
    provenance_line,
    sidecar_document,
    solve_floor,
    validate_emitted_keys,
    write_json,
)
from advntr.background_capture import (
    Capture,
    CaptureObservation,
    Observation,
    load_capture,
    parse_decision_log,
    read_sink,
)
from advntr.background_validation import (
    REQUIRED_LABEL_FIELDS,
    _StaticModel,
    aggregation_fidelity,
    blocked_folds,
    cross_validate,
    discrimination_ratios,
    k_versus_n_regression,
    load_accuracy_bench,
    load_labels,
    model_from_fit,
    replay_sample,
    shuffle_probabilities,
    truncation_ratios,
)

__all__ = [
    'ABLATION_EPSILON', 'BackgroundFit', 'Capture', 'CaptureObservation',
    'FitterError', 'GRAMMAR_COMPONENT', 'HYPERPARAMETERS', 'MAX_PROBABILITY',
    'Observation', 'REQUIRED_LABEL_FIELDS', 'SETTINGS_MIN_SUPPORTING_READ_COUNT',
    'SIMULATED_DISCLAIMERS', 'SINK_SCHEMA', 'SINK_VERSION', '_StaticModel',
    'aggregation_fidelity', 'artifact_document', 'blocked_folds', 'class_of',
    'cross_validate', 'default_disclaimers', 'discrimination_ratios',
    'fit_background', 'grammar_states', 'is_compound', 'k_versus_n_regression',
    'load_accuracy_bench', 'load_capture', 'load_labels', 'median',
    'model_from_fit', 'parse_decision_log', 'provenance_line', 'read_sink',
    'replay_sample', 'sidecar_document', 'shuffle_probabilities', 'solve_floor',
    'truncation_ratios', 'validate_emitted_keys', 'write_json',
]
